-- Migration: Add Instamart and Zepto Analytics Tables

-- 1. INSTAMART TABLES
CREATE TABLE instamart_sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand TEXT NOT NULL,
  item_id TEXT NOT NULL,
  item_name TEXT,
  manufacturer_id TEXT,
  city_id INTEGER,
  city_name TEXT,
  category TEXT,
  sale_date DATE NOT NULL,
  qty_sold INTEGER DEFAULT 0,
  mrp DECIMAL(10,2) DEFAULT 0,
  uploaded_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE instamart_inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand TEXT NOT NULL,
  snapshot_date DATE NOT NULL,
  facility_name TEXT,
  facility_code INTEGER,
  item_id TEXT NOT NULL,
  item_name TEXT,
  backend_inv INTEGER DEFAULT 0,
  frontend_inv INTEGER DEFAULT 0,
  uploaded_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ZEPTO TABLES
CREATE TABLE zepto_sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand TEXT NOT NULL,
  item_id TEXT NOT NULL,
  item_name TEXT,
  manufacturer_id TEXT,
  city_id INTEGER,
  city_name TEXT,
  category TEXT,
  sale_date DATE NOT NULL,
  qty_sold INTEGER DEFAULT 0,
  mrp DECIMAL(10,2) DEFAULT 0,
  uploaded_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE zepto_inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand TEXT NOT NULL,
  snapshot_date DATE NOT NULL,
  facility_name TEXT,
  facility_code INTEGER,
  item_id TEXT NOT NULL,
  item_name TEXT,
  backend_inv INTEGER DEFAULT 0,
  frontend_inv INTEGER DEFAULT 0,
  uploaded_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ENABLE RLS
ALTER TABLE instamart_sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE instamart_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE zepto_sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE zepto_inventory ENABLE ROW LEVEL SECURITY;

-- 4. POLICIES (Sales)
CREATE POLICY "Users see their brand instamart sales" ON instamart_sales
  FOR SELECT USING (brand IN (SELECT brand_slug FROM brands WHERE brand_id IN (SELECT brand_id FROM user_brands WHERE user_id = auth.uid())));

CREATE POLICY "Users see their brand zepto sales" ON zepto_sales
  FOR SELECT USING (brand IN (SELECT brand_slug FROM brands WHERE brand_id IN (SELECT brand_id FROM user_brands WHERE user_id = auth.uid())));

-- 5. POLICIES (Inventory)
CREATE POLICY "Users see their brand instamart inventory" ON instamart_inventory
  FOR SELECT USING (brand IN (SELECT brand_slug FROM brands WHERE brand_id IN (SELECT brand_id FROM user_brands WHERE user_id = auth.uid())));

CREATE POLICY "Users see their brand zepto inventory" ON zepto_inventory
  FOR SELECT USING (brand IN (SELECT brand_slug FROM brands WHERE brand_id IN (SELECT brand_id FROM user_brands WHERE user_id = auth.uid())));

-- 6. INSERT PERMISSIONS
CREATE POLICY "Users can insert their brand instamart sales" ON instamart_sales FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can insert their brand instamart inventory" ON instamart_inventory FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can insert their brand zepto sales" ON zepto_sales FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can insert their brand zepto inventory" ON zepto_inventory FOR INSERT WITH CHECK (true);

-- 7. GRANT PERMISSIONS
GRANT ALL ON instamart_sales TO authenticated;
GRANT ALL ON instamart_inventory TO authenticated;
GRANT ALL ON zepto_sales TO authenticated;
GRANT ALL ON zepto_inventory TO authenticated;
